name = "demo"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.37.0 and < 1.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"
plinth = ">= 0.2.0 and < 1.0.0"
htmb = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_fetch = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
lustre = ">= 4.2.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
